version: "3.9"
   
services:
  redis:
    image: redis
    container_name: autocli_redis
    command: redis-server
    ports:
      - "14000:6379"
  db:
    image: postgres
    container_name: autocli_db
    environment:
      - POSTGRES_USER=tutorial
      - POSTGRES_PASSWORD=tutorial
      - POSTGRES_DB=tutorial
    ports:
      - "5005:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    build: .
    restart: always
    command: > 
      "
      python manage.py makemigrations
      python manage.py migrate  
      python manage.py runserver 0.0.0.0:8000
      "
    container_name: autocli_backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    links:
      - db
      - redis
    depends_on:
      - db
      - redis

networks:
  commandapp-network:
    driver: bridge