# Generated by Django 4.0.2 on 2022-02-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_usesettings_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usesettings',
            name='id',
            field=models.CharField(default='xeom6-bhba2-9uthv-cdkp0-p6yxc-6xdrx', editable=False, max_length=35, primary_key=True, serialize=False),
        ),
    ]
