# Generated by Django 4.0.2 on 2022-02-21 12:57

import autocli.basemodel.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_usesettings_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usesettings',
            name='description',
            field=models.CharField(default='Model description.', error_messages={'invalid': 'Enter the correct description value. It must contain 8 to 256 digits, letters and special characters -, _, . or spaces.'}, help_text='Xxx.', max_length=256, validators=[autocli.basemodel.validators.DescriptionValueValidator()], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='usesettings',
            name='name',
            field=models.CharField(error_messages={'blank': 'Name field is mandatory.', 'invalid': 'Enter the correct name value. It must contain 3 to 32 digits, letters or special characters -, _ or spaces.', 'null': 'Name field is mandatory.', 'unique': 'Object with this name already exists.'}, help_text='Xxx.', max_length=32, unique=True, validators=[autocli.basemodel.validators.NameValueValidator()], verbose_name='Name'),
        ),
    ]
