# Generated by Django 4.0.2 on 2022-02-19 20:18

import autocli.basemodel.validators
from django.db import migrations, models
import inventory.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_credential_folder_certificate_folder_https_port_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credential',
            options={'verbose_name': 'Credential', 'verbose_name_plural': 'Credentials'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.CharField(editable=False, max_length=35, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Object create date.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Object last update date.', verbose_name='Updated')),
                ('deleted', models.BooleanField(default=False)),
                ('root', models.BooleanField(default=False, help_text='Root object is not deletable.', verbose_name='Root')),
                ('active', models.BooleanField(default=True, help_text='Status of Model object.', verbose_name='Active')),
                ('name', models.CharField(error_messages={'blank': 'Name field is mandatory.', 'invalid': 'Enter the correct name value. It must contain 4 to 32 digits, letters and special characters -, _ or spaces.', 'null': 'Name field is mandatory.', 'unique': 'Model with this name already exists.'}, max_length=32, unique=True, validators=[autocli.basemodel.validators.NameValueValidator()])),
                ('description', models.CharField(default='Model description.', error_messages={'invalid': 'Enter the correct description value. It must contain 8 to 256 digits, letters and special characters -, _, . or spaces.'}, max_length=256, validators=[autocli.basemodel.validators.DescriptionValueValidator()])),
                ('hexadecimal', models.CharField(error_messages={'blank': 'Colour field is mandatory.', 'invalid': 'Enter the correct colour value. It must be a 3/6 hexadecimal number with # character on begining.', 'null': 'Colour field is mandatory.', 'unique': 'Color with this hexadecimal value already exists.'}, help_text='Color hexadecimal value.', max_length=7, unique=True, validators=[inventory.validators.ColorValueValidator()], verbose_name='Color')),
                ('credentials', models.ManyToManyField(blank=True, help_text='All credentials that belonge to current color.', to='inventory.Credential', verbose_name='Credentials')),
                ('devices', models.ManyToManyField(blank=True, help_text='All devices that belonge to current color.', to='inventory.Device', verbose_name='Devices')),
                ('folders', models.ManyToManyField(blank=True, help_text='All folder that belonge to current color.', to='inventory.Folder', verbose_name='Folders')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
    ]
