# Generated by Django 4.0.2 on 2022-02-13 08:58

import administration.validators
import autocli.basemodel.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'verbose_name': 'Administrator', 'verbose_name_plural': 'Administrators'},
        ),
        migrations.AlterModelOptions(
            name='administratorgroup',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterField(
            model_name='administrator',
            name='active',
            field=models.BooleanField(default=True, help_text='Status of Model object.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Object create date.', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='email',
            field=models.EmailField(blank=True, error_messages={'blank': 'E-mail field is mandatory.', 'invalid': 'Enter the correct e-mail value.', 'null': 'E-mail field is mandatory.', 'unique': 'Administrator with this e-mail already exists.'}, help_text='Administrator e-mail address.', max_length=128, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='first_name',
            field=models.CharField(blank=True, error_messages={'blank': 'First name field is mandatory.', 'invalid': 'Enter the correct first name value. It must contain 4 to 32 digits, letters and special characters -, _ or spaces.', 'null': 'First name field is mandatory.', 'unique': 'First name with this name already exists.'}, help_text='Administrator first name.', max_length=32, null=True, validators=[administration.validators.NameValueValidator()], verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='last_name',
            field=models.CharField(blank=True, error_messages={'blank': 'Last name field is mandatory.', 'invalid': 'Enter the correct last name value. It must contain 4 to 32 digits, letters and special characters -, _ or spaces.', 'null': 'Last name field is mandatory.', 'unique': 'Last name with this name already exists.'}, help_text='Administrator last name.', max_length=32, null=True, validators=[administration.validators.NameValueValidator()], verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='middle_name',
            field=models.CharField(blank=True, error_messages={'blank': 'Middle name field is mandatory.', 'invalid': 'Enter the correct middle name value. It must contain 4 to 32 digits, letters and special characters -, _ or spaces.', 'null': 'Middle name field is mandatory.', 'unique': 'Middle name with this name already exists.'}, help_text='Administrator middle name.', max_length=32, null=True, validators=[administration.validators.NameValueValidator()], verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='password',
            field=models.CharField(error_messages={'blank': 'Password field is mandatory.', 'invalid': 'Enter the correct password value. It requires at least one lowercase letter, one uppercase letter, one digit and one special character (@$!%*?&), minimum 8 characters.', 'null': 'Password field is mandatory.'}, help_text='Administrator password.', max_length=128, validators=[administration.validators.PasswordValueValidator()], verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='root',
            field=models.BooleanField(default=False, help_text='Root object is not deletable.', verbose_name='Root'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Object last update date.', verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='username',
            field=models.CharField(error_messages={'blank': 'Username field is mandatory.', 'invalid': 'Enter the correct username value. It must contain 4 to 32 digits, letters and spaces.', 'null': 'Username field is mandatory.', 'unique': 'Administrator with this username already exists.'}, help_text='Administrator username.', max_length=32, unique=True, validators=[administration.validators.UsernameValueValidator()], verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='administratorgroup',
            name='active',
            field=models.BooleanField(default=True, help_text='Status of Model object.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='administratorgroup',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Object create date.', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='administratorgroup',
            name='description',
            field=models.CharField(default='Model description.', error_messages={'invalid': 'Enter the correct description value. It must contain 8 to 256 digits, letters and special characters -, _, . or spaces.'}, max_length=256, validators=[autocli.basemodel.validators.DescriptionValueValidator()]),
        ),
        migrations.AlterField(
            model_name='administratorgroup',
            name='root',
            field=models.BooleanField(default=False, help_text='Root object is not deletable.', verbose_name='Root'),
        ),
        migrations.AlterField(
            model_name='administratorgroup',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Object last update date.', verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='active',
            field=models.BooleanField(default=True, help_text='Status of Model object.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Object create date.', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='description',
            field=models.CharField(default='Model description.', error_messages={'invalid': 'Enter the correct description value. It must contain 8 to 256 digits, letters and special characters -, _, . or spaces.'}, max_length=256, validators=[autocli.basemodel.validators.DescriptionValueValidator()]),
        ),
        migrations.AlterField(
            model_name='settings',
            name='name',
            field=models.CharField(error_messages={'blank': 'Name field is mandatory.', 'invalid': 'Enter the correct name value. It must contain 4 to 32 digits, letters and special characters -, _ or spaces.', 'null': 'Name field is mandatory.', 'unique': 'Model with this name already exists.'}, max_length=32, unique=True, validators=[autocli.basemodel.validators.NameValueValidator()]),
        ),
        migrations.AlterField(
            model_name='settings',
            name='root',
            field=models.BooleanField(default=False, help_text='Root object is not deletable.', verbose_name='Root'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Object last update date.', verbose_name='Updated'),
        ),
    ]
